### ISSUE TITLE
Tracker potential improvements

### ISSUE THREAD

**Issue by tdurand** [opendatacam/node-moving-things-tracker#10]
The IOU tracker published in december 2018 an extension of their paper that seems to use some of the improvement we already included here: predicting missing frame to avoid id reassignment.. but maybe worth a deeper look to find some new ideas.

Extending IOU Based Multi-Object Tracking by Visual Information (december 2018) : http://elvera.nue.tu-berlin.de/files/1547Bochinski2018.pdf

**Comment by tdurand** [comment]
related: https://github.com/bochinski/iou-tracker/issues/7

**Comment by tdurand** [comment]
Also, upcoming results of the 2019 MOT challenge the 16 june, would be interesting to see if there are new approachs : https://motchallenge.net/results/CVPR_2019_Tracking_Challenge/

cc @b-g

**Comment by alainmouttham** [comment]
Bonjour Thibaud,

We are new to OpenDataCam and may not be using it correctly, but we ran into some Tracker problem when there is occlusion. We are using Yolov3 on the Jetson TX2 and also the Nano just for comparison. Here is the problem:
* ODC tracks Object A (bike) correctly. Object A then remains fixed for the rest of the sequence
* Object B (person) comes into the picture and is tracked correctly, until Object B partially occludes Object A.
* Then Object B gets the label assigned to Object A which is not identified any longer.
* Object B moves out of the picture, and continues to be tracked incorrectly as Object A

We are working on the latest version of ODC; so you may have already implemented the IOU-based MOT algorithm. Its associated paper says upfront that the algorithm doesn't work well when there is significant occlusion, as in our case. You mentioned elsewhere that you are also looking at an improvement brought by the SORT algorithm, where Kalman Filtering and the Hungarian algorithm for Assignment are used. Have you implemented these?

Merci pour votre aide! ODC est un super projet!
Alain

**Comment by tdurand** [comment]
Hi Alain !

Many thanks for your comment.

Yes the tracker won't handle very well occlusion, it is very basic, it is based on the overlapping areas of the objects so it might get id reassignment in that case, as you said, it is based on the IOU tracker. We didn't experiment with Kalman Filtering and the Hungarian algorithm yet.

So the case you mentioned seems very normal with OpenDataCam, you are using it correctly !

We didn't dedicate time yet to improve this, so we are very open to contribution and feedback regarding this.

The most likely next improvement happening for us regarding the tracker will be to integrate improvement from the V-IOU paper, which the author is gonna publish the code and has got very good result in the latest MOT challenge: https://github.com/bochinski/iou-tracker/issues/7

**Comment by tdurand** [comment]
Code for V-IOU tracker has been published: https://github.com/bochinski/iou-tracker/issues/7#issuecomment-579816194

**Comment by vsaw** [comment]
V-IOU would be difficult to implement in ODC as we would need to make sure the JSON and MJPEG streams are in synch, otherwise we would extract outdated visual information. As this is not possible right now and would require significant refactoring in ODC, I propose to close the issue for now.
