### ISSUE TITLE
add stabilization?

### ISSUE THREAD

**Issue by gherkins** [opendatacam/node-moving-things-tracker#16]
how about adding position stabilization while already having a list of frames?    
I'd think that'd be a great additional feature for a tracker, wouldn't it?

as seen in https://github.com/tawnkramer/CarND-Vehicle-Detection#3-stablization

**Comment by tdurand** [comment]
hi, could you be more specific ?

**Comment by gherkins** [comment]
hey, maybe just return the average position of the last n:configurable frames...  
That would make for a much smoother movement of tracking frames when displayed.

**Comment by tdurand** [comment]
what would be the method to compute the average position for moving objects ?

**Comment by gherkins** [comment]
i guess you'd have to feed a relatively short list of frames to prevent lagging,  
but maybe implementing one of those would be worth a try:
https://www.npmjs.com/package/moving-averages

**Comment by tdurand** [comment]
ok, yes but we can't do that as we are computing in real time, we just know the next and previous frame to perform tracking ;-)

**Comment by gherkins** [comment]
🤔  i thought that would make it fairly easy to keep the n last frames and output the moving average position instead of the actual exact position.

but of course you can do that on top of the tracking from outside...

thx anyway!

**Comment by tdurand** [comment]
yes, but you can't display in real time in this case... Don't get me wrong, you are very welcome to send a Pull Request will this feature added that we could enable as an extra feature
