### ISSUE TITLE
Browser Support / Guide

### ISSUE THREAD

**Issue by ronalson** [opendatacam/node-moving-things-tracker#27]
Hello there!

Do you have any demo project or guide on how to use `node-moving-things-tracker` in the browser?

**Comment by vsaw** [comment]
Hi, sorry I missed your message. 

Short answer: No

Long answer: Never tried to compile it for the Browser. If you manage to get it compiled for the browser, using the tracker is fairly straight forward as the API is quite simple as there's one function to feed it raw objects and then you'll get tracker data right away. 

Sorry I can not be of more assistance right now
