### ISSUE TITLE
Add example running in browser

### ISSUE THREAD

**Issue by b-g** [opendatacam/node-moving-things-tracker#9]
Can take care of this ... we could take one of the BTT videos and play it back in a p5.js sketch (left side: video + raw yolo detection results, right side: video + yolo detection results filtered with moving-things-tracker).

@tdurand Do you have some good ugly raw yolo detection results? (tbd in our call this afternoon)

**Comment by tdurand** [comment]
Nice idea, you have all the raw detections of BTT here: https://github.com/moovel/lab-beat-the-traffic/blob/master/static/levels/berlin-level1/rawdetections.txt

**Comment by tdurand** [comment]
You have the corresponding vimeoId here to download the footage: https://github.com/moovel/lab-beat-the-traffic/blob/master/gameconfig.json#L158

For example, berlin-1 is : https://vimeo.com/257858774

**Comment by tdurand** [comment]
_PS:

Also I'm thinking that on the command line code we are doing some extra logic on the beat the traffic data : https://github.com/tdurand/node-moving-things-tracker/blob/master/main.js#L72  , filtering out big detections and keeping only some classes before feeding it to the tracker.js ...

As you will feed the detections directly in the tracker without running this logic this could change a bit the results but for the demo example it will be fine._

**Comment by vsaw** [comment]
Closed because of inactivity.
